version: '3.1'

services:
    monit:
        build: .
        container_name: monit
        restart: always
        volumes:
            - ./proc:/proc:ro
            - monitdata:/var/monit
        networks:
            monit:

volumes:
    monitdata:
networks:
    monit:
        external: true