version: '3.1'

services:
    api:
        build: .
        container_name: api
        restart: always
        user: '5000'
        ports:
            - "8080:8080"
        volumes:
            - ./api/apiConf.json:/etc/monit/config.json
            - ./api:/app
        environment:
            - TZ=Europe/Paris
        networks:
            monit:

networks:
    monit:
        external: true