# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monit.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmonit.proto\x12\x05monit\x1a\x1bgoogle/protobuf/empty.proto\"\x0e\n\x0c\x43heckRequest\"&\n\x0fGetLastResponse\x12\x13\n\x0bresult_json\x18\x01 \x01(\t2\x7f\n\x0cMonitService\x12\x34\n\x05\x43heck\x12\x13.monit.CheckRequest\x1a\x16.google.protobuf.Empty\x12\x39\n\x07GetLast\x12\x16.google.protobuf.Empty\x1a\x16.monit.GetLastResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'monit_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHECKREQUEST']._serialized_start=51
  _globals['_CHECKREQUEST']._serialized_end=65
  _globals['_GETLASTRESPONSE']._serialized_start=67
  _globals['_GETLASTRESPONSE']._serialized_end=105
  _globals['_MONITSERVICE']._serialized_start=107
  _globals['_MONITSERVICE']._serialized_end=234
# @@protoc_insertion_point(module_scope)
