version: '3.1'

services:
    monit:
        build: .
        container_name: monit
        restart: always
        user: '5000'
        ports:
            - "50051:50051"
        volumes:
            - /proc:/proc
            - monitdata:/var/monit
            - ./monit/serverConf.json:/etc/monit/config.json
        networks:
            monit:

volumes:
    monitdata:
networks:
    monit:
        external: true
